### ISSUE TITLE
Hyperlinking website with https will cause a privacy error on google chrome

### ISSUE THREAD

**Issue by suoken** [baseballhackday/baseballhackday.github.io#103]
### Steps to Reproduce
Create a hyperlink to the website [https://baseballhackday.com/toronto](https://baseballhackday.com/toronto) in Google Chrome and click on the link. 

### Expected Behavior

The regular baseballhackday.com website shows 

### Actual Behavior
![image](https://user-images.githubusercontent.com/22568107/53639684-ecf5bf80-3bf7-11e9-9106-0304f45d1268.png)

Get a privacy error popup 

Maybe this should be an issue we should be tackling in case we have people hyperlinking the website with https? I guess the workaround is to not include https in any hyperlinks when doing promotions.

**Comment by daigofuji** [comment]
Yeah, I am using github pages and it is not https, so linking to this http://www.baseballhackday.com/toronto/ works. But I will see if I can get ssl certificate?

**Comment by daigofuji** [comment]
Looks like github side fixed this. Now this works https://www.baseballhackday.com/ closing this.
