### ISSUE TITLE
Post 2015 BBHD to do list

### ISSUE THREAD

**Issue by daigofuji** [baseballhackday/baseballhackday.github.io#16]
- [x] Add in Montreal & SF so everyone is under one roof -- follow up with other cities interested
- [x] Add a “Host a Baseball hack day in your city” link to rules around starting one up in your city (Daigo)
- [x] Combine the current style with Montreal’s style (Warren/Kyle)
- [ ] Add winners of each location plus all other projects to give people a good idea of what to expect out of the day
- [ ] Add photos of each of the events on their page to continue to set expectations on what to expect
- [x] Change register to email sign up (Daigo)

**Comment by atlas5d-matt** [comment]
@daigofuji anything in this list that would still be good to do?
